import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Providers from "@/providers/providers";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Just Astronomy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        {" "}
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-900`}
        >
          <div className="min-h-screen">{children}</div>
          <Toaster position="bottom-right" richColors />
        </body>
      </Providers>
    </html>
  );
}
